export const ADD_TIME_TABLE = "ADD_TIME_TABLE";

// TRAINER ACTIONS
export const ADD_TRAINER = "ADD_TRAINER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";

// FILIERE ACTIONS
export const ADD_PHARMACY = "ADD_PHARMACY";
export const EDIT_PHARMACY = "EDIT_PHARMACY";
export const DELETE_PHARMACY = "DELETE_PHARMACY";


// ROOM ACTIONS
export const ADD_ROOM = "ADD_ROOM";
export const EDIT_ROOM = "EDIT_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";


// SECTOR ACTIONS
export const ADD_EVENT = "ADD_EVENT";
export const EDIT_EVENT = "EDIT_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";

export const ADD_MEDICAMENT = "ADD_MEDICAMENT";
export const EDIT_MEDICAMENT = "EDIT_MEDICAMENT";
export const DELETE_MEDICAMENT = "DELETE_MEDICAMENT";

//  USER ACTIONS
export const SET_USER = "SET_USER"
export const REMOVE_USER = "REMOVE_USER"
